using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OmniUdp.Handler {
  /// <summary>
  ///   Describes a class that can handle events generated by the application.
  /// </summary>
  interface IEventHandlingStrategy {
    /// <summary>
    ///   Handle an event that should be treated as an error.
    /// </summary>
    /// <param name="payload">The payload to send with the event.</param>
    void HandleErrorEvent( byte[] payload );

    /// <summary>
    ///   Handle an event that should be treated as a UID being successfully read.
    /// </summary>
    /// <param name="payload">The payload to send with the event.</param>
    void HandleUidEvent( byte[] payload );
  }
}
